### ISSUE TITLE
Missing module `cbor-js`

### ISSUE THREAD

**Issue by julien-f** [vijayee/cuckoo-filter#5]
```js
require('cuckoo-filter');
```

```
> node index.js
{ Error: Cannot find module 'cbor-js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18) code: 'MODULE_NOT_FOUND' }
```

**Comment by alanshaw** [comment]
https://github.com/vijayee/cuckoo-filter/pull/6
